export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO'
export const MUTATE_ADD_TODO = 'MUTATE_ADD_TODO'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'
